# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: pacyu
email: darkchii@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  .
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mahoushi_
github_username:  pacyu

# Build settings
theme: tale
remote_theme: chesterhow/tale

url: "https://pacyu.github.io" # the base hostname & protocol for your site

plugins:
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-paginate

author: pacyu
avatar:	avatar.jpg
skin: daylight
lang: zh-cn
date_format: "%Y-%m-%d"
permalink: /:year-:month-:day/:title
paginate: 5
paginate_path: "page:num"
disqus: "pacyu"
google_analytics: "G-0BF2ZJ4TKZ"
